# Generated by Django 6.0.4 on 2026-04-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo_solicitud', models.CharField(choices=[('ACAD', 'Académica'), ('ADMIN', 'Administrativa'), ('TECN', 'Técnica'), ('OTRA', 'Otra')], default='ACAD', max_length=5)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
            ],
        ),
    ]
